# Generated by Django 4.1 on 2024-04-12 11:59

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("demo", "0002_remove_student_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="communitywishcourse",
            name="ttimestamp",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="wishcourse",
            name="timestamp",
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
