# Generated by Django 4.1 on 2024-04-12 12:00

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("demo", "0003_communitywishcourse_ttimestamp_wishcourse_timestamp"),
    ]

    operations = [
        migrations.RenameField(
            model_name="communitywishcourse",
            old_name="ttimestamp",
            new_name="timestamp",
        ),
    ]
