# Generated by Django 4.1 on 2024-04-12 12:04

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("demo", "0004_rename_ttimestamp_communitywishcourse_timestamp"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="communitywishcourse",
            name="timestamp",
        ),
        migrations.RemoveField(
            model_name="wishcourse",
            name="timestamp",
        ),
    ]
