# Generated by Django 4.1 on 2024-04-12 13:51

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("demo", "0006_communitywishcourse_timestamp_wishcourse_timestamp"),
    ]

    operations = [
        migrations.DeleteModel(
            name="CommunityMember",
        ),
    ]
