# Generated by Django 4.1 on 2024-04-14 07:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("demo", "0008_studentsimilarity_coursesimilarity"),
    ]

    operations = [
        migrations.AddField(
            model_name="student",
            name="name",
            field=models.CharField(default="Jack", max_length=200),
            preserve_default=False,
        ),
    ]
