# Generated by Django 4.1 on 2024-04-24 09:03

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("demo", "0011_message"),
    ]

    operations = [
        migrations.AddField(
            model_name="community",
            name="activity_level",
            field=models.FloatField(
                default=0.0,
                validators=[
                    django.core.validators.MaxValueValidator(1),
                    django.core.validators.MinValueValidator(0),
                ],
            ),
        ),
        migrations.AddField(
            model_name="community",
            name="gender_ratio",
            field=models.FloatField(
                default=0.5,
                validators=[
                    django.core.validators.MaxValueValidator(1),
                    django.core.validators.MinValueValidator(0),
                ],
            ),
        ),
        migrations.AddField(
            model_name="community",
            name="learning_style",
            field=models.FloatField(
                default=0.0,
                validators=[
                    django.core.validators.MaxValueValidator(1),
                    django.core.validators.MinValueValidator(0),
                ],
            ),
        ),
        migrations.AddField(
            model_name="communitycompletedcourse",
            name="member_ratio",
            field=models.FloatField(
                default=0.0,
                validators=[
                    django.core.validators.MaxValueValidator(1),
                    django.core.validators.MinValueValidator(0),
                ],
            ),
        ),
        migrations.AddField(
            model_name="communitywishcourse",
            name="member_ratio",
            field=models.FloatField(
                default=0.0,
                validators=[
                    django.core.validators.MaxValueValidator(1),
                    django.core.validators.MinValueValidator(0),
                ],
            ),
        ),
        migrations.AddField(
            model_name="student",
            name="activity_level",
            field=models.FloatField(
                default=0.0,
                validators=[
                    django.core.validators.MaxValueValidator(1),
                    django.core.validators.MinValueValidator(0),
                ],
            ),
        ),
        migrations.AddField(
            model_name="student",
            name="gender",
            field=models.IntegerField(choices=[(0, "女"), (1, "男")], default=0),
        ),
        migrations.AddField(
            model_name="student",
            name="learning_style",
            field=models.IntegerField(
                choices=[(0, "未知"), (1, "发散型"), (2, "同化型"), (3, "聚敛型"), (4, "顺应型")],
                default=0,
            ),
        ),
        migrations.AddField(
            model_name="student",
            name="self_description",
            field=models.TextField(blank=True, null=True),
        ),
    ]
