# Generated by Django 4.1 on 2024-04-25 14:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("demo", "0012_community_activity_level_community_gender_ratio_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="HomoStudentSimilarity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("similarity_vector", models.JSONField()),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="homo_similarity_vector",
                        to="demo.student",
                    ),
                ),
            ],
        ),
    ]
